"""
Django settings for busbooking project.

Generated by 'django-admin startproject' using Django 6.0.1.
"""

from pathlib import Path
import os  # <<< TAMBAHAN >>>

from dotenv import load_dotenv  # <<< TAMBAHAN >>>

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env (root project)
load_dotenv(BASE_DIR / ".env")  # <<< TAMBAHAN >>>


# ==============================
# Core settings
# ==============================

SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-fallback-key"
)  # <<< PERUBAHAN >>>

DEBUG = os.environ.get("DEBUG", "False").lower() in ("true", "1", "yes")  # <<< PERUBAHAN >>>

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "").split() if not DEBUG else []  # <<< PERUBAHAN >>>


# ==============================
# Application definition
# ==============================

INSTALLED_APPS = [
    "corsheaders",  # <<< TAMBAHAN >>>

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "booking",
    "easy_thumbnails",
    "image_cropping",

]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",

    "corsheaders.middleware.CorsMiddleware",  # <<< TAMBAHAN >>>
    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "busbooking.urls"


# ==============================
# Templates
# ==============================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "busbooking.wsgi.application"


# ==============================
# Database (SQLite)
# ==============================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# ==============================
# Password validation
# ==============================

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# ==============================
# Internationalization
# ==============================

LANGUAGE_CODE = os.environ.get("LANGUAGE_CODE", "id")  # <<< PERUBAHAN >>>
TIME_ZONE = os.environ.get("TIME_ZONE", "Asia/Jakarta")  # <<< PERUBAHAN >>>

USE_I18N = True
USE_TZ = True


# ==============================
# Static & Media files
# ==============================

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# ==============================
# Session settings (PENTING untuk seat hold)
# ==============================

SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_AGE = 60 * 60
SESSION_SAVE_EVERY_REQUEST = True

# Cookies: untuk session + CSRF saat React beda origin (dev)
SESSION_COOKIE_SAMESITE = "Lax"  # <<< TAMBAHAN >>>
CSRF_COOKIE_SAMESITE = "Lax"     # <<< TAMBAHAN >>>

SESSION_COOKIE_SECURE = False    # <<< TAMBAHAN >>> (True jika HTTPS)
CSRF_COOKIE_SECURE = False       # <<< TAMBAHAN >>> (True jika HTTPS)


# ==============================
# CORS + CSRF (React Frontend)
# ==============================

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",   # Vite
    "http://127.0.0.1:5173",   # Vite alt
    "http://localhost:3000",   # CRA (opsional)
    "http://127.0.0.1:3000",   # CRA alt (opsional)
]  # <<< TAMBAHAN >>>

CORS_ALLOW_CREDENTIALS = True  # <<< TAMBAHAN >>>

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]  # <<< TAMBAHAN >>>


# ==============================
# Admin API Key (proteksi endpoint admin)
# ==============================

ADMIN_API_KEY = os.environ.get("ADMIN_API_KEY", "")


# ==============================
# Default primary key
# ==============================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
