# Generated by Django 6.0.1 on 2026-01-15 03:18

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_seat_booking_code_trip_admin_wa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='bus_image',
            field=models.ImageField(blank=True, null=True, upload_to='trip_bus/'),
        ),
        migrations.AddField(
            model_name='trip',
            name='bus_image_cropping',
            field=image_cropping.fields.ImageRatioField('bus_image', '1600x896', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='bus image cropping'),
        ),
    ]
